### ISSUE TITLE
Build fails in fuerte

### ISSUE THREAD

**Issue by mkoval** [personalrobotics/herb_description#2]
The build reliably fails with the two errors:

```
<DOM Element: xacro:include at 0x2f83998>
Traceback (most recent call last):
  File "/opt/ros/fuerte/stacks/xacro/xacro.py", line 35, in <module>
    xacro.main()
  File "/opt/ros/fuerte/stacks/xacro/src/xacro.py", line 554, in main
    process_includes(doc, os.path.dirname(sys.argv[1]))
  File "/opt/ros/fuerte/stacks/xacro/src/xacro.py", line 202, in process_includes
    raise XacroException("included file \"%s\" could not be opened: %s" % (filename, str(e)))
xacro.XacroException: included file "bh280.urdf.xacro" could not be opened: [Errno 2] No such file or directory: 'bh280.urdf.xacro'
[ 65%] make[3]: *** [../robots/bh280.urdf] Error 1
<DOM Element: xacro:include at 0x2847bd8>
Traceback (most recent call last):
  File "/opt/ros/fuerte/stacks/xacro/xacro.py", line 35, in <module>
    xacro.main()
  File "/opt/ros/fuerte/stacks/xacro/src/xacro.py", line 554, in main
    process_includes(doc, os.path.dirname(sys.argv[1]))
  File "/opt/ros/fuerte/stacks/xacro/src/xacro.py", line 202, in process_includes
    raise XacroException("included file \"%s\" could not be opened: %s" % (filename, str(e)))
xacro.XacroException: included file "herb_base.urdf.xacro" could not be opened: [Errno 2] No such file or directory: 'herb_base.urdf.xacro'
```

This seems to be related to some missing dependencies when doing an in-source build. However, I haven't been able to track them down.

**Comment by brianhou** [comment]
Closing since we haven't used Fuerte in a while :sweat_smile:
